eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:9090/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
    com.capgemini: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

finflow:
  environment: "development"
