server:
  port: 8081

finflow:
  message: "Hello World from Auth Service!"

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3037/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false

---
spring:
  config:
    activate:
      on-profile: dev

finflow:
  message: "Hello World from Auth Service! (DEV Profile)"

---
spring:
  config:
    activate:
      on-profile: prod

finflow:
  message: "Hello World from Auth Service! (PROD Profile)"
